// Boneyard Registry - Auto-generated skeleton definitions
// This file contains bone snapshots for all Skeleton components in the application
// Auto-generated by boneyard-js build - do not edit manually

const bones = {
  'dashboard-metric-1': '<div class="h-32 bg-card border border-border rounded-lg p-4 animate-pulse"><div class="h-8 bg-gray-200 rounded w-full mb-3"></div><div class="h-8 bg-gray-200 rounded w-20"></div></div>',
  'dashboard-metric-2': '<div class="h-32 bg-card border border-border rounded-lg p-4 animate-pulse"><div class="h-8 bg-gray-200 rounded w-full mb-3"></div><div class="h-8 bg-gray-200 rounded w-20"></div></div>',
  'dashboard-metric-3': '<div class="h-32 bg-card border border-border rounded-lg p-4 animate-pulse"><div class="h-8 bg-gray-200 rounded w-full mb-3"></div><div class="h-8 bg-gray-200 rounded w-20"></div></div>',
  'dashboard-timeline': '<div class="h-96 bg-card border border-border rounded-lg p-4 animate-pulse"></div>',
  'dashboard-schedule': '<div class="h-48 bg-card border border-border rounded-lg p-4 animate-pulse"><div class="space-y-3"><div class="h-20 bg-secondary rounded-lg"></div><div class="h-20 bg-secondary rounded-lg"></div></div></div>',
  'dashboard-actions': '<div class="h-48 bg-background rounded-lg p-4 animate-pulse"></div>',
  'dashboard-appointments': '<div class="space-y-3"><div class="h-20 bg-secondary border-l-2 border-ring rounded-2xl p-4 animate-pulse"></div><div class="h-20 bg-secondary border-l-2 border-ring rounded-2xl p-4 animate-pulse"></div><div class="h-20 bg-secondary border-l-2 border-ring rounded-2xl p-4 animate-pulse"></div></div>',
  'patients-grid': '<div class="space-y-6"><div class="h-16 bg-background rounded-lg animate-pulse"></div><div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"><div class="h-64 bg-card border border-border rounded-lg animate-pulse"></div><div class="h-64 bg-card border border-border rounded-lg animate-pulse"></div><div class="h-64 bg-card border border-border rounded-lg animate-pulse"></div></div></div>',
  'sessions-data-table': '<div class="h-96 bg-card border border-border rounded-lg p-4 animate-pulse"></div>',
}

export default bones
